### DISCUSSION TITLE
How kube-green to sleep specific resource

### DISCUSSION THREAD

**Discussion by rafael-tomelin** [kube-green/kube-green#545] [Q&A]
Hi team,

How can I configure to sleep one resource?

I need configure the one Rollout from ArgoCD to sleep but I didn't understand the configuration about the patches for it.

```
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: sleep-rollout
spec:
  weekdays: "1-5"
  sleepAt: "20:00"
  wakeUpAt: "06:00"
  timeZone: "America/Sao_Paulo"
  includeRef:
    - matchLabels: 
           app.kubernetes.io/name: myapp-name
  patches:
    - target:
        group: argoproj.io
        kind: Rollout
      patch: |-
        - op: replace
          path: /spec/replicas
          value: 0
```
