### DISCUSSION TITLE
Kubegreen Schedule: Weekday Sleep & Weekend Shutdown

### DISCUSSION THREAD

**Discussion by Sanketarali** [kube-green/kube-green#547] [Q&A]
Hi , I need help configuring a pod schedule using Kubegreen:

Weekdays (Mon–Fri): Pods should sleep at 10 PM and wake up at 10 AM.

Weekends (Sat–Sun): Pods should be completely shut down, and wake up Monday at 10 AM.

What's the best way to set this up in Kubegreen?

Thanks in advance! 🙏

**Comment by davidebianchi** [comment]
Hi @Sanketarali! Something like the below should work:

```yaml
spec:
  weekdays: "1-5" # from monday to friday
  sleepAt: "22:00"
  wakeUpAt: "10:00"
  timeZone: "" # set the timezone of interest
```
