### DISCUSSION TITLE
How to Configure Sleep/Wake Times in Kubegreen for Weekday Nights and Weekends ( Indian Standard timezone )

### DISCUSSION THREAD

**Discussion by Sanketarali** [kube-green/kube-green#551] [Q&A]
Hi team, 👋
I'm trying to configure Kubegreen to automatically sleep and wake pods based on the following schedule:

📅 Weekday Schedule (IST timezone)
Sleep: 10:00 PM IST (Monday–Friday)
Wake: 9:00 AM IST (Monday–Friday)

🛌 Weekend Schedule
Sleep: Friday 8::00 PM IST
Wake: Sunday 11:00 AM IST

Would really appreciate an example or guidance on how to set this up correctly. 🙏

**Comment by davidebianchi** [comment]
Hi @Sanketarali!

It is not possible at the moment to address it with a single SleepInfo, it requires the update in #393. 
At the moment, it should be possible to create 2 different SleepInfo, one with:

```yaml
wakeUpAt: 09:00
sleepAt: 22:00
weekdays: 1-5
timeZone: Asia/Kolkata
```

and another with:

```yaml
wakeUpAt: 08:00
sleepAt: 20:00
weekdays: 0,6
timeZone: Asia/Kolkata
```

This is not exactly as you desired, as also on sunday it wil sleep at 20:00. Also, it is not sure that the wake up would be done in correct way. To address correctly the requirement, we need to update the controller completing the linked PR.
