### ISSUE TITLE
Suspend only cronjobs?

### ISSUE THREAD

**Issue by AmitBaranes** [kube-green/kube-green#165]
is it possible to suspend only cronjobs? I've tested the following template but no luck -

```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours
spec:
  weekdays: "*"
  sleepAt: "16:30"
  wakeUpAt: "10:00"
  timeZone: "Asia/Jerusalem"
  suspendCronJobs: true
  excludeRef:
    - apiVersion: "apps/v1"
      kind: Deployment
      name: "*"
```
