### ISSUE TITLE
Cluster-wide SleepInfo and namespace exclusion

### ISSUE THREAD

**Issue by ams0** [kube-green/kube-green#167]
For cluster with large number of namespaces, it would be more convenient to set a new CRD called `ClusterSleepInfo` that operates across all namespaces, with default exclusion of kube-system and option list of namespaces and resources to exclude:

```yaml
apiVersion: kube-green.com/v1alpha1
kind: ClusterSleepInfo
metadata:
  name: working-hours
spec:
  weekdays: "1-5"
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
  excludeRef:
    - apiVersion: "apps/v1"
      kind:       Deployment
      name:       my-deployment
    - apiVersion: "v1"
      kind:       Namespace
      name:       my-namespace
```

I am aware of the implications here (controller needs access to every namespace) but it sounds like a good idea (at least to me!)
