### ISSUE TITLE
GitOps support

### ISSUE THREAD

**Issue by jkleinlercher** [kube-green/kube-green#259]
Does this work also when those resources are managed by a gitops agent like fluxcd or argocd? If not, what needs to be done to make it work? I think this is really a good project!

**Comment by davidebianchi** [comment]
Hi @jkleinlercher, really interesting use case!
At the moment we have not experience with kube-green working with argocd and fluxcd.
A possible way could be set some sync window to exclude the specific hours to the sync workload of the GitOps operators.

There is this comment of @victorboissiere https://github.com/kube-green/kube-green/issues/142#issuecomment-1415944043, which uses Argo and could be useful to use kube-green in this context.

This is a really interesting and increasingly widespread use case, so I think we should add some guideline and documentation about this, and go deep to know if there is a way to improve integration.

**Comment by henobi** [comment]
Hello,
I tried kube-green with a ArgoCD managed workload. I had to switch off `selfHeal` in the ArgoCD Application because otherwise I noticed ArgoCD was instantly restoring the amount of replicas deflagrating the effect of kube-green.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: false
```

Now during the shut off periods it is marked as out of sync in ArgoCD:
<img width="1108" alt="Bildschirmfoto 2024-08-24 um 23 23 32" src="https://github.com/user-attachments/assets/c948a337-5654-4a5f-87bb-aed950973d4d">

But it works now.

**Comment by bakaut** [comment]
We use a flux with drift correction enabled for giops and find  an issue:

Infinity loop for drift correction of resources`ClusterRole/kube-green-manager-role`
```
kubectl -n flux-system describe hr kube-green
Events:
  Type     Reason         Age                 From             Message
  ----     ------         ----                ----             -------
  Warning  DriftDetected  14m (x28 over 70m)  helm-controller  Cluster state of release tools/kube-green.v1 has drifted from the desired state:
ClusterRole/kube-green-manager-role changed (0 additions, 1 changes, 0 removals)
  Normal  DriftCorrected  14m (x14 over 70m)  helm-controller  Cluster state of release tools/kube-green.v1 has been corrected:
ClusterRole/kube-green-manager-role configured
```

We use official helm chart 0.7.0 version of kube-green

Possible workaround https://github.com/fluxcd/flux2/issues/2472#issuecomment-1862770622
Or ignore /role path for `ClusterRole/kube-green-manager-role` with [flux ](https://fluxcd.io/flux/components/helm/helmreleases/#drift-correction)

Would it be possible to drop `rules: []` from https://github.com/kube-green/kube-green/blob/main/charts/kube-green/templates/cluster_role.yaml#L79 to prevent such types of issues?

**Comment by davidebianchi** [comment]
I'm not sure it's ok the resource without the rules array. It would be worth doing a test to verify that it works correctly. If it works, it's ok to remove it.

**Comment by bakaut** [comment]
@davidebianchi thanks for feedback

**Comment by ehrnst** [comment]
I'm evaluating options and came across kube green. Immediately, I thought how would this work with flux. If I am scripting this, i would suspend all flux kustomizations, and scale down the deployments. It would be great if kube-green could do something similar

**Comment by bakaut** [comment]
@ehrnst we used kubegreen patch to suspend helm releases

```yaml
---
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: scale-up-down
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  weekdays: "*"
  sleepAt: "01:00"
  suspendCronJobs: true
  # Patches applied when the cluster 'goes to sleep'
  patches:
  - target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
    patch: |-
      - path: /spec/suspend
        op: add
        value: true
```

You may suspend flux kustomizations using kubegreen patch functional

**Comment by ehrnst** [comment]
@bakaut interesting. but i guess you have to specify all kustomizations then?

**Comment by christianhuth** [comment]
We solved this problem by using Sync Windows for ArgoCD and basically denying a Sync during the kube-green Schedule. But you have to create an algorithm that translates the kube-green schedule (fixed endtime with wakeUpAt) to the sync windows logic (duration beginning from the starttime).

**Comment by lemonzst** [comment]
Hey, I am using ArgoCD and didn't like the idea of using sync waves, or switching off `selfHeal`.
Instead you can simply use `ignoreDifferences` in the ArgoCD application while specifying `managedFieldsManagers`.

For example:

```
  ignoreDifferences:
  - group: apps
    kind: Deployment
    managedFieldsManagers:
    - kube-green-controller-manager
    jsonPointers:
    - /spec/replicas
```

This ensures ArgoCD is still capable of automatically fixing drifts, and HPAs work as expected, while letting the deployments which were scaled to 0 _specifically_ by kube-green to stay down.
