### ISSUE TITLE
Sleep with TTL

### ISSUE THREAD

**Issue by AmitBaranes** [kube-green/kube-green#263]
As part of our testing process, we create a namespace with all microservices and 3rd parties for each developer as a namespace.
This namespace has a 72-hour TTL, pass that the namespace is destroyed automatically using a cronjob via K8S API.
Sometimes, this 72 hours is more than the developer needs to check the namespace, so we would like to put this namespace to sleep after 48 hours using kube-green and kill it after 72 hours.
This deletion can also be done manually but requires the developer to login into the cluster, which ends up having unused namespaces as a result of laziness. 

is it possible by using kube-green?

**Comment by davidebianchi** [comment]
This seems to be the same request as in issue [issue 61](https://github.com/kube-green/kube-green/issues/61).
Do you think it's the same use case? 
The idea is to create a new resources to handle the resource of ephemeral namespaces.
Are you interested in this feature?

At the moment, with kube-green is possible to stop the namespace without wake up unsettling the wakeUp field in the Sleepinfo.

Side note: are you interested to add your company to the list of adopters?

**Comment by AmitBaranes** [comment]
Yes, that seems like the same request.
+ is there an option to have multiple condition. like - suspend all cronjobs for good + sleep namespace on Saturday?
something like: 
```
# suspend all cronjobs all days
apiVersion: "kube-green.com/v1alpha1"
kind: "SleepInfo"
metadata:
 name: "cronjobs-suspend"
spec:
  weekdays: "*"
  sleepAt: "*:*"
  suspendCronJobs: true
  suspendDeployments: false
---
#sleep env at night and Saturday
apiVersion: "kube-green.com/v1alpha1"
kind: "SleepInfo"
metadata:
  name: "sleep-at-night-and-saturday"
spec:
  timeZone: "Asia/Jerusalem" # Change based on selected time-zone
  weekdays: "1-6"
  sleepAt: "21:00"
  wakeUpAt: "9:00"
  suspendDeployments: true
```
