### ISSUE TITLE
Option to deploy kube-green operator in a specific namespace

### ISSUE THREAD

**Issue by imdmahajankanika** [kube-green/kube-green#286]
The default option to deploy the operator is in openshift-operators. Is it possible to install it in user-defined namespace?

**Comment by davidebianchi** [comment]
Hi, it is possible directly with olm. 
At this documentation, it's explained how to install the operator in a specific namespace: https://docs.openshift.com/container-platform/4.12/operators/user/olm-installing-operators-in-namespace.html.

Just as example, you should create a `OperatorGroup` and a `Subscription` CRD.

This is the operator group, to apply in the namespace where you want to install the operator:

```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: PackageManifest.v1.packages.operators.coreos.com
  name: custom-namespace-operators
spec:
  upgradeStrategy: Default
```

And you should also create in this namespace a `Subscription`, something like this (changing accordingly the spec configuration):

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-kube-green
spec:
  channel: alpha
  name: kube-green
  source: operatorhubio-catalog
  sourceNamespace: olm
```

I close the issue since it is more related to olm, reopen it if this does not resolve the issue.
