### ISSUE TITLE
Sleep between Tuesday-Saturday, wake up Sunday

### ISSUE THREAD

**Issue by pelegz** [kube-green/kube-green#300]
Hello,

Is there an option to configure namespaces to sleep WHOLE days and wake up on a specific days?

We have workloads only running on Sundays. On the rest of the days, I'd like to scale down all deployments in our namespaces and only wake them up on Sundays.

Documentation says that I can only configure sleep and for waking them up I have to deploy the resources manually.
Is there a workaround?

Thank you!

**Comment by davidebianchi** [comment]
Hi @pelegz! To run workload only on Sundays, you can configure something like:

```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours
spec:
  weekdays: "0"
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
```

Where weekdays 0 is Sunday.
With this configuration, you sleep wake up workload on Sunday at 8am and sleep on Sunday at 20pm. So, the workload only running during Sunday. Obviously, you can change the time slot as you prefer.
