### ISSUE TITLE
Ability to sleep and wake up an entire cluster 

### ISSUE THREAD

**Issue by msfidelis** [kube-green/kube-green#309]
For operational efficiency, it would be interesting to have the ability to sleep and wake up one or more namespaces, or the entire cluster completely.

I believe using allow or deny expressions based on namespaces can help.

Example:

```yaml
---
apiVersion: kube-green.com/v1alpha1
kind: SleepCluster # Fictional Name
metadata:
  name: working-hours
spec:
  weekdays: "1-5"
  sleepAt: "20:00"
  wakeUpAt: "07:30"
  timeZone: "America/Sao_Paulo"
  suspendCronJobs: true
  excludeNamespaces:
    - kube-system
    - karpenter
    - kube-green
---
```
