### ISSUE TITLE
Need example of sleepInfo for full weekend stop.

### ISSUE THREAD

**Issue by bartleboeuf** [kube-green/kube-green#332]
Hello, we need to turn off our workload during the weekend from Friday evening at 21:00 PM until Monday 06:00 AM. We have tested different settings but we can't find a configuration that allows us to do this. Could you help us? And at the same time enrich the documentation with this type of configuration. Thank you for your help.

**Comment by davidebianchi** [comment]
Hello,

At the moment, this doesn't appear to be possible, as it works with both sleep and wake up all the weekdays it is configured to work. This could be an interesting use case to enhance the specification by include also this use case.

**Comment by dirk39** [comment]
Hello! I'd like to have a look at a possible implementation.

**Comment by davidebianchi** [comment]
Hi @dirk39! Sure, you're welcome! Do you have some idea or suggestion on how we should change the spec to support it?

**Comment by dirk39** [comment]
Hey @davidebianchi! I'm creating a general configuration that may also satisfy specific days of the year, like Xmas (#343 ). 
This was my initial Idea:
```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours-except-wednesday
spec:
  weekdays: "1-5"
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  customSleeps:
    - weekDaySleep: 2
      sleepTime: "20:00"
      weekDayWakeUp: 4
      wakeUpAtTime: "05:00"
  suspendCronJobs: true
```

My idea was to set `weekdays` and `sleepAt` optional and add the `customSleeps` configuration (optional). I'm concerned about the priority of applying the customSleeps, e.g., do we want to follow the list order? My definition does not support yet the holiday list.

**Comment by davidebianchi** [comment]
I agree, the priority it's a concern, and also manage the possible intersections between different configurations. Maybe we could think about to split the days configuration as you write, but writing only 1 time schedule per spec. To manage the holidays, we could add a list of specific days when the configuration should be suspended. What do you think about?

**Comment by dirk39** [comment]
How should the configuration suspension be interpreted? In the issue above, we need to keep the deployment running from Monday to Friday and stop it during the weekend. Could you provide an example of how the configuration might be?

**Comment by davidebianchi** [comment]
It could be something like:

```json
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours-except-wednesday
spec:
  weekDaySleep: 2
  sleepTime: "20:00"
  weekDayWakeUp: 4
  wakeUpAtTime: "05:00"
  weekdays: "1-5"
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  scheduleExceptions:
    - day: "25-12"
       suspend: true
  suspendCronJobs: true
```

Which is a merge with your propose adding the exceptions. What do you think about?

**Comment by dirk39** [comment]
I like your idea! My concern is: what do we consider a "suspension"? It must be considered an always sleep process?

**Comment by davidebianchi** [comment]
As suspend I supposed to do nothing, so if the last status is wake up, it remains for all the day in this state. And the same for the sleep.

But it could be quite misleading, maybe we could split in some field to avoid sleep and/or wake up specifically?

**Comment by dirk39** [comment]
Yes, my main concern is how we can manage three different use cases:
1. classic, e.g., `mon-fri  6-21`
2. exception: e.g., `mon-fri  6-21, (25/12|26/12) off`
3. inverted: e.g., `sat-sun Off, mon 6:00`

So, adjusting your example: 
Case 2: 
```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours-except-xmas
spec:
  weekdays: "1-5"
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  scheduleExceptions:
    - day: 25/12
      sleep: true
    - day: 26/12
      sleep: true   
  suspendCronJobs: true
```
Case 3: 
```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: weekend-off
spec:
  weekdays: "1-5"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  scheduleExceptions:
    - weekDay: 6
      sleep: true
    - weekDay: 7 
      sleep: true   
  suspendCronJobs: true
```
In the last example, we should make `sleepAt` not mandatory, and run the `sleepAt` at midnight on Saturday and Friday.

What do you think?

**Comment by davidebianchi** [comment]
Ok, I agree with the different use cases. 

The **classic use case** should be something like this: sleep and wake up every day, from Monday to Friday:

```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours-classic
spec:
  weekDaySleep: 1-5
  weekDayWakeUp: 1-5
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
```

---

The **xmas use case** should be something _classic + exceptions_.
The exceptions should allow the user to enable/disable step of the flow or to change the hours. Set only the boolean could be not powerful as it's needed maybe?
We could think the exception as a completely new configuration, only for the specific day. So, without set the `wakeUp` field, the namespace is not waked up. 

What do you think about?

```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours-except-xmas
spec:
  weekDaySleep: 1-5
  weekDayWakeUp: 1-5
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  scheduleExceptions:
    - day: "25-12"
       sleepAt: "08:00"
    - day: 26/12
       sleepAt: "08:00"
  suspendCronJobs: true
```

---

The **only weekend off use case**:

```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: only-weekend-off
spec:
  weekDaySleep: 6,0
  weekDayWakeUp: 1-5
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
```

**Comment by dirk39** [comment]
I like it! I'll open a Draft PR ASAP so you can monitor the changes.

**Comment by mdhomer** [comment]
Hi all, I just started looking at this project to potentially use in my workplace for "sleeping" our development deployments (unused over the weekends). I was following this thread and wanted to offer an alternative to the working-hour/only-weekend-off api design.

This may be harder to implement, however I thought it might be easier to configure by having 2 different CRD objects `SleepInfoDaily` & `SleepInfoWeekly` for the 2 usecases.
I.e:
```
apiVersion: kube-green.com/v1alpha1
kind: SleepInfoDaily
metadata:
  name: working-hours-classic
spec:
  weekDaySleep: 1-5
  weekDayWakeUp: 1-5
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
```
```
apiVersion: kube-green.com/v1alpha1
kind: SleepInfoWeekly
metadata:
  name: only-weekend-off
spec:
  daySleep: 5
  sleepAt: "20:00"
  dayWakeUp: 1
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
```

Any thoughts would be appreciated and ofc happy to help if this is an avenue you'd like to follow!

**Comment by davidebianchi** [comment]
Hi @mdhomer, thank you for the proposal! So, the proposal is to create another CRD to manage the weekly sleep, is it right?

The second configuration could be reached with the previous proposal in this way:

```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: only-weekend-off
spec:
  weekDaySleep: 5
  weekDayWakeUp: 1
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
```

Which is quite equal to your proposal. What are the advantages to create another CRD?

**Comment by mdhomer** [comment]
Hi @davidebianchi, that was my proposal! But perhaps due to my naivety I thought the above configuration wasn't possible with the previous CRD.

You're approach looks good for this case.

Just one other suggestion, for the exception case:

```yml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours-except-xmas
spec:
  weekDaySleep: 1-5
  weekDayWakeUp: 1-5
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  scheduleExceptions:
    - date: "25-12"
       sleepAt: "08:00"
    - date: 26/12
       sleepAt: "08:00"
  suspendCronJobs: true
  ```
  
It might be better to use `date` rather than `day` to describe the input, especially if you plan to parse this?

Otherwise the classic CRD with these options seems straight forward to me :)
