### ISSUE TITLE
Installing thru OperatorHub UI not possible

### ISSUE THREAD

**Issue by dbarreda** [kube-green/kube-green#335]
When trying to install on Openshift thru OperatorHub it auto-selects the installation namespace "openshift-operators" which errors out with this.

![image](https://github.com/kube-green/kube-green/assets/2085427/2416a8a1-5631-4549-acb8-ddc80ee57be1)

**Comment by davidebianchi** [comment]
Hi @dbarreda, it is not possible to select another namespace where to install it? 

If you want to install kube-green in the `openshift-operators` namespace, you should check that the OperatorGroup inside this namespace is something like:

```yaml
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: all-namespaces-operator-group
  namespace: openshift-operators
```

You can check more about it here: https://olm.operatorframework.io/docs/advanced-tasks/operator-scoping-with-operatorgroups/
