### ISSUE TITLE
Prometheus scrape metrics

### ISSUE THREAD

**Issue by blezoray** [kube-green/kube-green#427]
Hello,

I deployed kube-green with OLM on an Openshift platform and I would like to configure my local Prometheus to scrape its metrics.
But, when I try to configure it, queries returns `server returned HTTP status 400 Bad Request` on both ports 8443 and 9443.

After some investigation, it appears that /metrics is exposed only on the localhost:
```yaml
    spec:
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
```

There is also a service named `kube-green-controller-manager-metrics-service` on port 8443. But it is protected by the sidecar `kube-rbac-proxy` and a query returns `401 Unauthorized`.

What is the solution to bypass the kube-rbac-proxy ?

Rgds.
