### ISSUE TITLE
Support 'sleep' to a custom replica count

### ISSUE THREAD

**Issue by cool2k** [kube-green/kube-green#436]
While it is very useful to sleep to a count of 0. In some cases there can be Carbon benefits by forcing a scale down to a custom replica count.
Without this capability, I can see several missed opportunities that won't use kube-green or will need to create their own solution in order to keep maybe at least 1 replica for some services.
I think this is still a good use case towards the goal.

Thoughts?

**Comment by davidebianchi** [comment]
Hi @cool2k! With the new 0.6.0 version it will be possible to manage custom logic to the changed resource, so it would be possible to set replicas count to 1 for example. If you are interested, you can try [v0.6.0-rc.1](https://github.com/kube-green/kube-green/releases/tag/v0.6.0-rc.1).

Otherwise, it is not the possibility to use the HPA to manage the horizontal autoscaling to 1, if 0 is not needed?

**Comment by wvengen** [comment]
I've been trying to use `patch` for this, and discovered that I should keep `suspendDeployments` set to `true`, otherwise the deployments would be skipped. I was a bit puzzled to understand how built-in and custom patches are applied when both are present (did see a `disableDefaultPatches` suggestion in a code comment), but it seems that the custom patch is actually honoured.

```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
# ...
spec:
  # ...
  patches:
  - patch: |
      - path: "/spec/replicas"
        op: "add"
        value: 1
    target:
      group: apps
      kind: deployment
```
