### ISSUE TITLE
Support for CloudNativePG

### ISSUE THREAD

**Issue by henobi** [kube-green/kube-green#470]
Hello,
first of all: really cool project!! 

One thing that would be really cool would be the integration of the very common Postgres operator cloudnative PG (https://cloudnative-pg.io/).

The start and stop of a postgres cluster is handled by a annotation:

### Stop
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgcluster
  namespace: devpoc
  annotations:
    cnpg.io/hibernation: "on"
spec:
  instances: 1
  storage:
    size: 5Gi
```
