### ISSUE TITLE
Include specific deployment in the sleepinfo

### ISSUE THREAD

**Issue by joudaon** [kube-green/kube-green#498]
Hello,

I have two deployments in the namespace "my-test-namespace":

- myapp1
- myapp2

And I have the following sleepinfo:

```
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: sleep-myapp1
  namespace: my-test-namespace
spec:
  patches:
  - patch: |-
      - path: /metadata/annotations/autoscaling.keda.sh~1paused-replicas
        op: add
        value: "0"
      - path: /metadata/annotations/autoscaling.keda.sh~1paused
        op: add
        value: "true"
    target:
      group: keda.sh
      kind: ScaledObject
  sleepAt: "08:00"
  suspendCronJobs: true
  suspendDeployments: true
  timeZone: Europe/Madrid
  wakeUpAt: "12:00"
  weekdays: "*"
  includeRef:
    - apiVersion: "apps/v1"
      kind: Deployment
      name: myapp1
```

Actual behaviour: it suspends both deployments "myapp1" and "myapp2"

Desired behaviour: only suspend "myapp1" deployment

**Comment by davidebianchi** [comment]
Hi @joudaon!
It is possible to filter the target deployment using     `includeRef` to include some resource or `excludeRef` to exclude that. 
Including more than one resource is only possible using labels, for only 1 resource per kind it is possible also with name. [Here](https://kube-green.dev/docs/apireference_v1alpha1/) you can see the API reference, and [here](https://kube-green.dev/docs/configuration/) an example configuration.

**Comment by joudaon** [comment]
Hello @davidebianchi , 
I am already using includeRef to include only myapp1 deployment, but both apps are being shutdown.

Do I need to exclude myapp2? If that namespace had 3 apps, I should exclude the other 2 apart from including myapp1?

Thanks.

**Comment by joudaon** [comment]
I have also tried with labels without any luck:

apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: sleep-myapp1
  namespace: my-test-namespace
spec:
  patches:
  - patch: |-
      - path: /metadata/annotations/autoscaling.keda.sh~1paused-replicas
        op: add
        value: "0"
      - path: /metadata/annotations/autoscaling.keda.sh~1paused
        op: add
        value: "true"
    target:
      group: keda.sh
      kind: ScaledObject
  sleepAt: "08:00"
  suspendCronJobs: true
  suspendDeployments: true
  timeZone: Europe/Madrid
  wakeUpAt: "12:00"
  weekdays: "*"
  includeRef:
    - matchLabels: 
        app: myapp1

**Comment by joudaon** [comment]
I am using 0.6.0 version

**Comment by davidebianchi** [comment]
There is keda on `myapp1` and `myapp2`? It could be that the replicas are changed by keda, changing the autoscaling resource? 
If this is the case, you should include the autoscaling resource to manage

**Comment by joudaon** [comment]
Yes, both apps are using Keda ScaledObjetc. We should target that object resource right?

```
includeRef:
    - apiVersion: "<kedaAPIversion"
      kind: ScaledObject
      name: myapp1
```

**Comment by davidebianchi** [comment]
Yes, correct. If all deployments are managed by Keda you could avoid that kube-green manage it directly (setting the `suspendDeployments` fields to false or including also the deployment by name).
Otherwise, kube-green will turn off the deployments and keda will turn on. At the end the result is the same, but it would be better to avoid to change the resources if not needed.

**Comment by joudaon** [comment]
Hi,

That worked perfectly!

Thank you.

```
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: sleep-myapp1
  namespace: my-test-namespace
spec:
  patches:
  - patch: |-
      - path: /metadata/annotations/autoscaling.keda.sh~1paused-replicas
        op: add
        value: "0"
      - path: /metadata/annotations/autoscaling.keda.sh~1paused
        op: add
        value: "true"
    target:
      group: keda.sh
      kind: ScaledObject
  sleepAt: "08:00"
  suspendCronJobs: true
  suspendDeployments: true
  timeZone: Europe/Madrid
  wakeUpAt: "12:00"
  weekdays: "*"
  includeRef:
    - apiVersion: "keda.sh/v1alpha1"
      kind: ScaledObject
      name: myapp1
```
