### ISSUE TITLE
Hardcoded namespace in the certificate template file

### ISSUE THREAD

**Issue by kimllee** [kube-green/kube-green#501]
Hello,

Thanks a lot for this awesome app updated !
Looks like there's a problem when we try to install the helm-chart kube-green 0.6.0 in another namespace than kube-green.
The certificate template is using the hard-coded namespace in its file.

Terraform code : 

```
resource "helm_release" "kube_green" {
  name = "kube-green"
  #chart            = "${path.module}/helm-chart"
  chart      = "kube-green"
  repository = "https://kube-green.github.io/helm-charts/"
  #version          = "0.5.2"
  version = "0.6.0"
  timeout = 600
  namespace        = "toolbox"
  create_namespace = true
  lint             = true
  skip_crds        = false
  values = [
    "${file("${var.kube_green_values_file}")}"
  ]

  depends_on = [resource.google_compute_firewall.webhook]
}
```

This how I have managed it when we used the 0.5.2 to deploy the chart in another namespace.

```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-green-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    #  - kube-green-webhook-service.kube-green.svc
    #  - kube-green-webhook-service.kube-green.svc.cluster.local
    - kube-green-webhook-service.{{ include "kube-green.namespace" . }}.svc
    - kube-green-webhook-service.{{ include "kube-green.namespace" . }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kube-green-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kube-green-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    # cert-manager.io/inject-ca-from: kube-green/kube-green-serving-cert
    cert-manager.io/inject-ca-from: {{ include "kube-green.namespace" . }}/kube-green-serving-cert
  creationTimestamp: null
  name: kube-green-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: kube-green-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-kube-green-com-v1alpha1-sleepinfo
    failurePolicy: Fail
    name: vsleepinfo.kb.io
    rules:
      - apiGroups:
          - kube-green.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - sleepinfos
    sideEffects: None

```

Thank you :)
