### ISSUE TITLE
[proposal] extending kube-green to support time-shifted Jobs

### ISSUE THREAD

**Issue by ryansingman** [kube-green/kube-green#542]
## Proposal: Adding FlexibleJob and FlexibleCronJob CRDs for Carbon-Aware Scheduling

Hello! First, thank you for your excellent work on `kube-green`. I've been exploring ways to enhance Kubernetes sustainability practices and believe `kube-green` is uniquely positioned to offer even greater value to environmentally-conscious Kubernetes users.

### Context

Currently, `kube-green` supports the `SleepInfo` CRD, enabling users to schedule downtime for deployments, stateful sets, and cron jobs—effectively reducing unnecessary resource usage. This aligns perfectly with recognized green software practices.

However, there is another sustainability opportunity that is currently untapped: time-shifting Kubernetes Jobs and CronJobs based on carbon intensity forecasts.

### Proposal

I'd like to contribute an extension to `kube-green` by introducing two new CRDs:

- **FlexibleJob**
- **FlexibleCronJob**

These new CRDs would allow users to specify flexible time windows for running Jobs and CronJobs. A scheduler, leveraging real-time carbon intensity data (using the [carbon-aware-sdk](https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/dev)), would execute these workloads at times when the carbon impact is lowest.

### Alignment with Green Software Foundation

This approach directly aligns with [the Green Software Foundation's documented patterns](https://patterns.greensoftware.foundation/catalog/cloud/time-shift-kubernetes-cron-jobs) on "Time Shifting Cron Jobs"—highlighting a recognized yet underserved sustainability pattern. To my knowledge, no existing open-source solution automatically implements this pattern within Kubernetes. Please do correct me if you're aware of something I'm missing here!

### Benefit to `kube-green`

By incorporating carbon-aware scheduling, `kube-green` could become a more comprehensive Kubernetes solution for sustainable resource management. This addition woul enhance the project's value proposition, enabling users to not only scale down but also intelligently schedule workloads to reduce carbon emissions.

### Next Steps

I'd be thrilled to discuss this further, outline implementation details, and prepare an initial contribution.

Would you be open to accepting such a feature?

Thank you for considering—I look forward to your thoughts!

**Comment by ryansingman** [comment]
> I'm unsure if insert it inside the kube-green repo, or instead create another operator inside the kube-green orgs to do it.
Definitely a good question! I think from a cohesive user experience perspective, it _would_ belong inside the `kube-green` repo.

However, the controllers for these resources do require usage of an external, protected API ([`Watttime`](https://watttime.org/)). Because of that, the install processes for `kube-green` would have to be amended to allow for the passing of a WattTime API Key (either in plaintext or as a secret). And of course, we'd want to make it such that users would be to install `kube-green` without requiring this WattTime integration.

I'll defer this decision to you, of course, but I think it would _probably_ be a better fit as a separate operator.

> Do you already have some implementation details, or an idea of the FlexibleJob and FlexibleCronJob spec?

Still iterating on the details (and would welcome any feedback you have), but these are my current specs:

(note -- renamed from `FlexibleJob` and `FlexibleCronJob` to `CarbonAwareJob` and `CarbonAwareCronJob`)
```
apiVersion: batch.kube-green.com/v1alpha1
kind: CarbonAwareJob
metadata:
  labels:
    app.kubernetes.io/name: carbon-aware-kube
    app.kubernetes.io/managed-by: kustomize
  name: carbonawarejob-sample
spec:
  startFlexWindowSeconds: 3600
  expectedDuration: 1800
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
---
apiVersion: batch.kube-green.com/v1alpha1
kind: CarbonAwareCronJob
metadata:
  labels:
    app.kubernetes.io/name: carbon-aware-kube
    app.kubernetes.io/managed-by: kustomize
  name: carbonawarecronjob-sample
spec:
  schedule: "- 0-3 * * *" # job can be run at any time between 00:00 and 03:59
  expectedDuration: 1800
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
