### ISSUE TITLE
having multiple sleepinfo resources created in same namespace with includeRef and exckudeRef is not working

### ISSUE THREAD

**Issue by amitkbaid** [kube-green/kube-green#549]
I have 2 sleepinfo resources created in the dev namespace. The first is defined to sleep everything except for statefulSets, (excluded using excludeRef) while 10 minutes later there is another sleepinfo resource which has been configured to sleep excluded statefulSets. 

**everything except for statefulSets to sleep at 23:40**

```
  spec:
    excludeRef:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: redis-master
    - apiVersion: apps/v1
      kind: StatefulSet
      name: redis-replicas
    sleepAt: "23:40"
    suspendCronJobs: true
    timeZone: Asia/Calcutta
    wakeUpAt: "09:10"
    weekdays: 1-5
```

**all statefulSet to sleep at 23:50**

```
  spec:
    includeRef:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: redis-master
    - apiVersion: apps/v1
      kind: StatefulSet
      name: redis-replicas
    sleepAt: "23:50"
    suspendCronJobs: true
    timeZone: Asia/Calcutta
    wakeUpAt: "09:00"
    weekdays: 1-5
```

the first sleepinfo resource sleeps everything except statefulSet, the other resource supposedly does not do anything (it does not sleep the statefulSet).

Is this expected, and if yes what could be a workaround if I would like to have something similar to be configured in my setup.

**Comment by davidebianchi** [comment]
Hi @amitkbaid! Due to how resource filtering works in Kubernetes, if you use an "includeRef" with names, you can only filter one resource per SleepInfo per kind of resource. Using two names in the filter results in none being returned. If you want to use a single SleepInfo for both, could you use labels for the "includeRef" instead?

So, something like:

```yaml
  spec:
    includeRef:
    - matchLabels: 
      component: redis
    sleepAt: "23:50"
    suspendCronJobs: true
    timeZone: Asia/Calcutta
    wakeUpAt: "09:00"
    weekdays: 1-5
```
