### ISSUE TITLE
kube-green v0.7.0 puts all deployments to sleep regardless of annotations or labels

### ISSUE THREAD

**Issue by Santh0712** [kube-green/kube-green#556]
We have deployed kube-green version v0.7.0 in our cluster and configured it with either annotationsSelector or labelsSelector to selectively suspend only certain deployments. However, at the scheduled sleep time, all deployments in the managed namespaces are being put to sleep, including those that are not annotated or labeled for suspension.

What we tried:

- Verified the annotationsSelector and labelsSelector configuration in the Helm values file.
- Ensured only specific deployments have the matching annotation (kube-green.dev/suspend: "true") or label.
- Confirmed excludeRef is set only for the kube-green controller deployment.
- Observed that every deployment in the namespace was suspended at the scheduled sleep time, not just the selected ones.

Expected behavior:
- Only deployments with the specified annotation or label should be suspended.

values file excerpt:

controller:
  namespaces:
    - platform
    - delivery
  annotationsSelector:
    enabled: true
    key: kube-green.dev/suspend
    value: "true"
  labelsSelector:
    enabled: false
  excludeRef:
    - apiVersion: apps/v1
      kind: Deployment
      name: kube-green-controller-manager

Any help or clarification on this would be appreciated.

**Comment by davidebianchi** [comment]
Hi @Santh0712! I'm not sure to have correctly understood. The `excludeRef` is set in the `values.yaml` file of the helm chart? It should be configured at SleepInfo level.

To suspend only the resource with specific labels, you should create a SleepInfo resource similar to:

```yaml
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: include-with-labels
spec:
  weekdays: "1-5"
  sleepAt: "20:00"
  wakeUpAt: "08:00"
  timeZone: "Europe/Rome"
  suspendCronJobs: true
  includeRef:
    - matchLabels: 
        kube-green.dev/suspend: true
```

in the selected namespace. If kube-green has not this labels, it should not be suspended.
