### ISSUE TITLE
Add combination of sleepAt options in one resource

### ISSUE THREAD

**Issue by Allure996** [kube-green/kube-green#97]
Hi, I was thinking about a way to combine more SleepInfo rules in only one resource.

Right now, to turn off a namespace, I have to create a `SleepInfo` resource defining `spec.weekdays` and `spec.sleepAt`.
If I would have to combine a more articulate way to make my namespace sleep I have to create more SleepInfos.

In my opinion, it would be nice to have the possibility to use only one SleepInfo manifest to manage this purpose, maybe having an array `sleepInfoRules`, that contains the different `sleepAt` values defined for different weekdays.

For example

```
spec:
  slpeeInfoRules:
    - weekdays: "1-5"
      sleepAt: "20:00"
      wakeUpAt: "07:00"
    - weekdays: "6-7"
      sleepAt: "00:00"   
```

**Comment by davidebianchi** [comment]
Hi @Allure996, interesting idea.
In a first release, I avoided to combine different rules because if the rules are overlapped it's difficult to predict the correct operation of the sleep lifecycle. 
It should be interesting to add the feature in a predictable way

**Comment by Allure996** [comment]
Hi @davidebianchi thanks for your answer.
I'm gonna try to make many sleepInfos overlap, and try to figure out if the right behaviour can be predicted

**Comment by gregoriopalama** [comment]
@davidebianchi is this still valid? I would like to help on this.
What would be the best way to address a situation where the sleepInfos overlap and, let's say, one tells to wake up when the other tells to put a resource to sleep? 

For example:
```
spec:
  sleepInfoRules:
    - weekdays: "1-5"
      sleepAt: "20:00"
      wakeUpAt: "07:00"
    - weekdays: "3-5"
      sleepAt: "21:00"   
      wakeUpAt: "05:00"
```

In this scenario, the rules are overlapping and incongruous. We could solve the issue with some assumptions, maybe raising a warning. If these rules have been set, maybe it's been for a mistake, or someone didn't read the previous rules before adding new ones. If so, then the best thing to do would be to merge the rules, and the first one would be the most important one. Kube-green is intended to put resources at sleep, after all, so making the largest rule win should be the correct behaviour. 
Otherwise, if these rules are intended, then something is off, and the warning should be enough to notify that they need to be rewritten.
